In [67]:
import numpy as np
np.random.seed(0)

def computation(p_values):
  output = np.empty(len(p_values))

  for i in range(len(p_values)):
    output[i]=1.0/p_values[i]

  return output



array([2.86726215e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       3.28094598e-085, 1.08645885e-071, 1.74248988e-076, 7.78817096e-091,
       6.23466669e+174, 6.01347153e-154])

In [60]:
values = np.random.randint(1,10,size=5)
values

array([6, 1, 4, 4, 8])

In [61]:
computation(p_values = values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [62]:
big_array = np.random.randint(1,100,size=1000000)
%timeit computation(p_values = big_array)

2.73 s ± 153 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [63]:
%timeit 1.0/big_array

1.48 ms ± 205 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [64]:
%timeit sum(big_array)

96.8 ms ± 17.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
%timeit np.sum(big_array)

901 µs ± 247 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [68]:
#np.ones
ones = np.ones((3,5), dtype=np.float32)
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [69]:
#np.zeros
zeros = np.zeros((6,2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [70]:
#создания массива 
array=np.arange(1334, 1338)
array

array([1334, 1335, 1336, 1337])

In [75]:
#соединение массивов
ones = np.ones((2,3))
zeros = np.zeros((4,3))
new = np.concatenate([ones,zeros])
new

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
#соединение массивов
ones = np.ones((4,1))
zeros = np.zeros((4,2))
new = np.concatenate([ones,zeros], axis=1)
new

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [76]:
A = np.array([[4670.5,4670.5,4670.5],
              [4670.5,4670.5,4670.5],
              [4670.5,4670.7,4670.5]])

A.astype(np.uint16)

array([[4670, 4670, 4670],
       [4670, 4670, 4670],
       [4670, 4670, 4670]], dtype=uint16)

In [77]:
A = np.ones((2,2,3))
print(A)
print("------------------")
B = np.zeros_like(A)
print(B)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
------------------
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [81]:
A = np.random.random((10,3))
A

array([[0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677],
       [0.43860151, 0.98837384, 0.10204481],
       [0.20887676, 0.16130952, 0.65310833],
       [0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959]])

In [99]:
a = np.arange(8).reshape(2,2,2)
print(a)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [98]:
a = a.T
a

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [101]:
a = a.transpose((1,0,2))
a

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])